### ISSUE TITLE
#hacktoberfest Make your first pull request (Begineers)

### ISSUE THREAD

**Issue by nikhilmufc7** [nikhilmufc7/Hacktoberfest-PR#1]
If you are a first-time contributer or you want to participate in hactoberfest and get yourself some cool stickers and t-shirt just add your names to the html with a link to your profile. Look at readme for more details.

Make sure you resolve the merge conflicts before making a PR

**Comment by sanghisha145** [comment]
When I tried to push to master as well as to new branch created to my local repository, permission denied. Can you look into this.

**Comment by nikhilmufc7** [comment]
@sanghisha145 Guessing you have not logged in with github on git. Anyways just fork and update the html as given in readme by going on to your own forked repo on github , would take 2-3 mins

**Comment by sanghisha145** [comment]
Thanks, actually after forking I had to clone my forked repo, did with original

**Comment by archieacharya** [comment]
does the name come immediately or after the merge is approved?
