### ISSUE TITLE
Add a footer section 

### ISSUE THREAD

**Issue by nikhilmufc7** [nikhilmufc7/Hacktoberfest-PR#17]
Add a footer with a link to register for hacktoberfest, nothing fancy.Use only bootstrap or CSS. Good first issue to get started with hacktoberfest.

**Comment by Mumbaikar007** [comment]
I am intrested to work on this issue :yum:

**Comment by nikhilmufc7** [comment]
Okay sure

**Comment by abderra7** [comment]
it's that already done?

**Comment by nikhilmufc7** [comment]
I guess @Mumbaikar007 is already working on it.
