### ISSUE TITLE
Increase font size 

### ISSUE THREAD

**Issue by nikhilmufc7** [nikhilmufc7/Hacktoberfest-PR#19]
Easy issue to get started, make font size a bit bigger , keep the font style same.

**Comment by humanforklift** [comment]
I'm keen to have a go at this. Just to clarify, is all text on the page to be increased?

**Comment by nikhilmufc7** [comment]
Yes only the text size @humanforklift

**Comment by amanjain97** [comment]
Please review my PR

**Comment by nikhilmufc7** [comment]
still need to increase font size of the usernames, you can take up that @humanforklift
