### ISSUE TITLE
Add a scroll view for mobile platforms

### ISSUE THREAD

**Issue by nikhilmufc7** [nikhilmufc7/Hacktoberfest-PR#33]
The usernames section is not visible on mobiles, maybe add a scroll view and fix it

**Comment by v-chmykov** [comment]
Hi :)

[#42](https://github.com/nikhilmufc7/Hacktoberfest-PR/pull/42/)

**Comment by nikhilmufc7** [comment]
it is still not scrollable on mobile mate
