### ISSUE TITLE
#Hacktoberfest Just add your name to HTML file [Beginners]

### ISSUE THREAD

**Issue by nikhilmufc7** [nikhilmufc7/Hacktoberfest-PR#71]
Looking to make most out of hacktoberfest but don't know where to contribute? just add your name to the html file in the list section and submit a pull request. Easiest way to get started with your open source contributions. Refer readme for more detailed instructions.

**Comment by akmittal** [comment]
I'm sorry but this is just cheating. Just for the sake of getting T-Shirt. 
Help people contribute to useful projects.

**Comment by nikhilmufc7** [comment]
T-shirt is a motivation, making people aware of open source and creating an easy way to create a Pull request is the motive. Almost half of the people contributing have not got any idea of how to make a pull request , if you think this is cheating then I can't help with it

**Comment by NickBellamy** [comment]
I just wanted to say thanks for this; I've never made a Pull request before on GitHub, and it's great to have a project that new people can contribute to.  It's so difficult to find opportunities for a first pull request, as there are always multiple people vying to contribute on every "newbie friendly" issue!

**Comment by DigitalDesignerOnline** [comment]
thanks for the repo, great way for us to increase awareness by showing just how many people are getting involved. :)

**Comment by jainayush975** [comment]
Added myself and created PR #157
